//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstExample
{
    using System;
    using System.Collections.Generic;
    using System.Data.Objects;

    public partial class ResgisterShopping
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Membership { get; set; }
        public string ShoppingPreference { get; set; }
        public string COD { get; set; }
        public string Password { get; set; }

        public static explicit operator ResgisterShopping(ObjectResult<sp_SelectRegisterShopping_Result> v)
        {
            throw new NotImplementedException();
        }
    }
}
